// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreSQL;

namespace Back.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Model.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("BrandID");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Model.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProductID");

                    b.HasKey("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Model.CartRecord", b =>
                {
                    b.Property<int>("CartRecordID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BuyDate");

                    b.Property<int>("Number");

                    b.Property<int>("Price");

                    b.Property<int?>("ProductID");

                    b.HasKey("CartRecordID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartRecords");
                });

            modelBuilder.Entity("Model.ChatRecord", b =>
                {
                    b.Property<int>("ChatRecordID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ChatRecordID");

                    b.ToTable("ChatRecords");
                });

            modelBuilder.Entity("Model.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Subject");

                    b.Property<int?>("UserID");

                    b.HasKey("CommentID");

                    b.HasIndex("UserID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Model.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<string>("Email");

                    b.Property<string>("Mobile");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Model.MultiMedia", b =>
                {
                    b.Property<int>("MultiMediaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MultiMediaTypeID");

                    b.Property<string>("Path");

                    b.HasKey("MultiMediaID");

                    b.HasIndex("MultiMediaTypeID");

                    b.ToTable("MultiMedias");
                });

            modelBuilder.Entity("Model.MultiMediaType", b =>
                {
                    b.Property<int>("MultiMediaTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("MultiMediaTypeID");

                    b.ToTable("MultiMediaTypes");
                });

            modelBuilder.Entity("Model.Nation", b =>
                {
                    b.Property<int>("NationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("NationID");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("Model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BrandID");

                    b.Property<bool>("Enabled");

                    b.Property<string>("Name");

                    b.Property<int?>("NationID");

                    b.HasKey("ProductID");

                    b.HasIndex("BrandID");

                    b.HasIndex("NationID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Model.ProductComment", b =>
                {
                    b.Property<int>("ProductCommentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProductID");

                    b.Property<int?>("ScoreCommentID");

                    b.HasKey("ProductCommentID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ScoreCommentID");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("Model.ProductMultiMedia", b =>
                {
                    b.Property<int>("ProductMultiMediaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MultiMediaID");

                    b.Property<int?>("ProductID");

                    b.HasKey("ProductMultiMediaID");

                    b.HasIndex("MultiMediaID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductMultiMedias");
                });

            modelBuilder.Entity("Model.ProductScore", b =>
                {
                    b.Property<int>("ProductScoreID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProductID");

                    b.Property<int?>("ScoreID");

                    b.HasKey("ProductScoreID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ScoreID");

                    b.ToTable("ProductScores");
                });

            modelBuilder.Entity("Model.ProductSeller", b =>
                {
                    b.Property<int>("ProductSellerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Number");

                    b.Property<long>("Price");

                    b.Property<int?>("ProductID");

                    b.Property<int?>("SellerID");

                    b.HasKey("ProductSellerID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SellerID");

                    b.ToTable("ProductSellers");
                });

            modelBuilder.Entity("Model.ProductSimilar", b =>
                {
                    b.Property<int>("ProductSimilarID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProductID");

                    b.Property<int?>("SimilarID");

                    b.HasKey("ProductSimilarID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SimilarID");

                    b.ToTable("ProductSimilars");
                });

            modelBuilder.Entity("Model.Record", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Subject");

                    b.HasKey("RecordID");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Model.Score", b =>
                {
                    b.Property<int>("ScoreID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Rank");

                    b.Property<int?>("UserID");

                    b.HasKey("ScoreID");

                    b.HasIndex("UserID");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Model.Seller", b =>
                {
                    b.Property<int>("SellerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("UserID");

                    b.HasKey("SellerID");

                    b.HasIndex("UserID");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Model.Similar", b =>
                {
                    b.Property<int>("SimilarID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProductID");

                    b.HasKey("SimilarID");

                    b.HasIndex("ProductID");

                    b.ToTable("Similars");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("NationalNumber");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.UserCart", b =>
                {
                    b.Property<int>("UserCartID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CartID");

                    b.Property<int?>("UserID");

                    b.HasKey("UserCartID");

                    b.HasIndex("CartID");

                    b.HasIndex("UserID");

                    b.ToTable("UserCarts");
                });

            modelBuilder.Entity("Model.UserCartRecord", b =>
                {
                    b.Property<int>("UserCartRecordID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CartRecordID");

                    b.Property<int?>("UserID");

                    b.HasKey("UserCartRecordID");

                    b.HasIndex("CartRecordID");

                    b.HasIndex("UserID");

                    b.ToTable("UserCartRecords");
                });

            modelBuilder.Entity("Model.UserChatRecord", b =>
                {
                    b.Property<int>("UserChatRecordID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChatRecordID");

                    b.Property<int?>("UserID");

                    b.HasKey("UserChatRecordID");

                    b.HasIndex("ChatRecordID");

                    b.HasIndex("UserID");

                    b.ToTable("UserChatRecords");
                });

            modelBuilder.Entity("Model.UserContact", b =>
                {
                    b.Property<int>("UserContactID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContactID");

                    b.Property<int?>("UserID");

                    b.HasKey("UserContactID");

                    b.HasIndex("ContactID");

                    b.HasIndex("UserID");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("Model.UserRecord", b =>
                {
                    b.Property<int>("UserRecordID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RecordID");

                    b.Property<int?>("UserID");

                    b.HasKey("UserRecordID");

                    b.HasIndex("RecordID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRecords");
                });

            modelBuilder.Entity("Model.Cart", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("Model.CartRecord", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("Model.Comment", b =>
                {
                    b.HasOne("Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.MultiMedia", b =>
                {
                    b.HasOne("Model.MultiMediaType", "MultiMediaType")
                        .WithMany()
                        .HasForeignKey("MultiMediaTypeID");
                });

            modelBuilder.Entity("Model.Product", b =>
                {
                    b.HasOne("Model.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID");

                    b.HasOne("Model.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationID");
                });

            modelBuilder.Entity("Model.ProductComment", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany("ProductComment")
                        .HasForeignKey("ProductID");

                    b.HasOne("Model.Comment", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreCommentID");
                });

            modelBuilder.Entity("Model.ProductMultiMedia", b =>
                {
                    b.HasOne("Model.MultiMedia", "MultiMedia")
                        .WithMany()
                        .HasForeignKey("MultiMediaID");

                    b.HasOne("Model.Product", "Product")
                        .WithMany("ProductMultiMedia")
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("Model.ProductScore", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany("ProductScore")
                        .HasForeignKey("ProductID");

                    b.HasOne("Model.Score", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreID");
                });

            modelBuilder.Entity("Model.ProductSeller", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany("ProductSeller")
                        .HasForeignKey("ProductID");

                    b.HasOne("Model.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID");
                });

            modelBuilder.Entity("Model.ProductSimilar", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany("ProductSimilar")
                        .HasForeignKey("ProductID");

                    b.HasOne("Model.Similar", "Similar")
                        .WithMany()
                        .HasForeignKey("SimilarID");
                });

            modelBuilder.Entity("Model.Score", b =>
                {
                    b.HasOne("Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.Seller", b =>
                {
                    b.HasOne("Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.Similar", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("Model.UserCart", b =>
                {
                    b.HasOne("Model.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartID");

                    b.HasOne("Model.User", "User")
                        .WithMany("UserCarts")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.UserCartRecord", b =>
                {
                    b.HasOne("Model.CartRecord", "CartRecord")
                        .WithMany()
                        .HasForeignKey("CartRecordID");

                    b.HasOne("Model.User", "User")
                        .WithMany("UserCartRecords")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.UserChatRecord", b =>
                {
                    b.HasOne("Model.ChatRecord", "ChatRecord")
                        .WithMany()
                        .HasForeignKey("ChatRecordID");

                    b.HasOne("Model.User", "User")
                        .WithMany("UserChatRecords")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.UserContact", b =>
                {
                    b.HasOne("Model.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactID");

                    b.HasOne("Model.User", "User")
                        .WithMany("UserContacts")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.UserRecord", b =>
                {
                    b.HasOne("Model.Record", "Record")
                        .WithMany()
                        .HasForeignKey("RecordID");

                    b.HasOne("Model.User", "User")
                        .WithMany("UserSearchs")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
